Try to split build into multiple jobs

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -8,26 +8,30 @@ on:
       - 'beta'
 
 jobs:
-  publish:
+  prepare:
     if: ${{ !github.event.act }} # skip during local actions testing
-    name: Publish
+    name: Prepare
     permissions:
       contents: write
     runs-on: ubuntu-latest
     steps:
-      - name: Maximize build space
-        uses: AdityaGarg8/remove-unwanted-software@v2
-        with:
-          remove-dotnet: true
-          remove-android: true
-          remove-haskell: true
-          remove-codeql: true
-          remove-docker-image: true
       - name: Checkout the repository
         uses: actions/checkout@v4
       - run: |
           sed -i "s/^version: [0-9\.]\+/version: ${{ github.ref_name }}/g" docker/config.yaml
           sed -i '/^[ \t]/s/.*/  ${{ github.ref_name }}/g' docker/web/nspanelmanager/web/templates/footer.html
+      - uses: stefanzweifel/git-auto-commit-action@v5
+        if: ${{ !github.event.act }} # skip during local actions testing
+        with:
+          commit_message: Push updated version back to repo
+          branch: "${{ steps.image_name.outputs.branch }}"
+  publish-x86:
+    if: ${{ !github.event.act }} # skip during local actions testing
+    name: Publish x86
+    run-on: ubuntu-latest
+    permissions:
+      actions: read
+    steps:
       - name: Get image name
         shell: bash
         id: image_name
@@ -44,21 +48,202 @@ jobs:
             echo "Cannot determine image name!"
             exit 1
           fi
-      - uses: stefanzweifel/git-auto-commit-action@v5
-        if: ${{ !github.event.act }} # skip during local actions testing
-        with:
-          commit_message: Push updated version back to repo
-          branch: "${{ steps.image_name.outputs.branch }}"
       - name: Login to DockerHub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - uses: yogeshlonkar/wait-for-jobs@v0
+        with:
+          jobs: 'prepare'
+      - name: Checkout the repository
+        uses: actions/checkout@v4
       - name: Publish
         uses: home-assistant/builder@master
         with:
           args: |
-            --all \
+            --i386 \
+            --target docker \
+            --image ${{ steps.image_name.outputs.image_name }} \
+            --version ${{ github.ref_name }} \
+            --release ${{ github.ref_name }} \
+            --docker-hub ${{ secrets.DOCKERHUB_USERNAME }}
+
+  publish-x86_64:
+    if: ${{ !github.event.act }} # skip during local actions testing
+    name: Publish x86_64
+    run-on: ubuntu-latest
+    permissions:
+      actions: read
+    steps:
+      - name: Get image name
+        shell: bash
+        id: image_name
+        run: |
+          if [ "${{ github.event.release.prerelease }}" != "true" ]; then
+            echo "Image name: NSPanelManager-{arch}"
+            echo "image_name=NSPanelManager-{arch}" >> $GITHUB_OUTPUT
+            echo "branch=main" >> $GITHUB_OUTPUT
+          elif [ "${{ github.event.release.prerelease }}" == "true" ]; then
+            echo "Image name: NSPanelManager-beta-{arch}"
+            echo "image_name=NSPanelManager-beta-{arch}" >> $GITHUB_OUTPUT
+            echo "branch=beta" >> $GITHUB_OUTPUT
+          else
+            echo "Cannot determine image name!"
+            exit 1
+          fi
+      - name: Login to DockerHub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - uses: yogeshlonkar/wait-for-jobs@v0
+        with:
+          jobs: 'prepare'
+      - name: Checkout the repository
+        uses: actions/checkout@v4
+      - name: Publish
+        uses: home-assistant/builder@master
+        with:
+          args: |
+            --amd64 \
+            --target docker \
+            --image ${{ steps.image_name.outputs.image_name }} \
+            --version ${{ github.ref_name }} \
+            --release ${{ github.ref_name }} \
+            --docker-hub ${{ secrets.DOCKERHUB_USERNAME }}
+
+  publish-armhf:
+    if: ${{ !github.event.act }} # skip during local actions testing
+    name: Publish armhf
+    run-on: ubuntu-latest
+    permissions:
+      actions: read
+    steps:
+      - name: Get image name
+        shell: bash
+        id: image_name
+        run: |
+          if [ "${{ github.event.release.prerelease }}" != "true" ]; then
+            echo "Image name: NSPanelManager-{arch}"
+            echo "image_name=NSPanelManager-{arch}" >> $GITHUB_OUTPUT
+            echo "branch=main" >> $GITHUB_OUTPUT
+          elif [ "${{ github.event.release.prerelease }}" == "true" ]; then
+            echo "Image name: NSPanelManager-beta-{arch}"
+            echo "image_name=NSPanelManager-beta-{arch}" >> $GITHUB_OUTPUT
+            echo "branch=beta" >> $GITHUB_OUTPUT
+          else
+            echo "Cannot determine image name!"
+            exit 1
+          fi
+      - name: Login to DockerHub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - uses: yogeshlonkar/wait-for-jobs@v0
+        with:
+          jobs: 'prepare'
+      - name: Checkout the repository
+        uses: actions/checkout@v4
+      - name: Publish
+        uses: home-assistant/builder@master
+        with:
+          args: |
+            --armhf \
+            --target docker \
+            --image ${{ steps.image_name.outputs.image_name }} \
+            --version ${{ github.ref_name }} \
+            --release ${{ github.ref_name }} \
+            --docker-hub ${{ secrets.DOCKERHUB_USERNAME }}
+
+  publish-armv7:
+    if: ${{ !github.event.act }} # skip during local actions testing
+    name: Publish ARMv7
+    run-on: ubuntu-latest
+    permissions:
+      actions: read
+    steps:
+      - name: Get image name
+        shell: bash
+        id: image_name
+        run: |
+          if [ "${{ github.event.release.prerelease }}" != "true" ]; then
+            echo "Image name: NSPanelManager-{arch}"
+            echo "image_name=NSPanelManager-{arch}" >> $GITHUB_OUTPUT
+            echo "branch=main" >> $GITHUB_OUTPUT
+          elif [ "${{ github.event.release.prerelease }}" == "true" ]; then
+            echo "Image name: NSPanelManager-beta-{arch}"
+            echo "image_name=NSPanelManager-beta-{arch}" >> $GITHUB_OUTPUT
+            echo "branch=beta" >> $GITHUB_OUTPUT
+          else
+            echo "Cannot determine image name!"
+            exit 1
+          fi
+      - name: Login to DockerHub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - uses: yogeshlonkar/wait-for-jobs@v0
+        with:
+          jobs: 'prepare'
+      - name: Checkout the repository
+        uses: actions/checkout@v4
+      - name: Publish
+        uses: home-assistant/builder@master
+        with:
+          args: |
+            --armv7 \
+            --target docker \
+            --image ${{ steps.image_name.outputs.image_name }} \
+            --version ${{ github.ref_name }} \
+            --release ${{ github.ref_name }} \
+            --docker-hub ${{ secrets.DOCKERHUB_USERNAME }}
+
+  publish-aarch64:
+    if: ${{ !github.event.act }} # skip during local actions testing
+    name: Publish aarch64
+    run-on: ubuntu-latest
+    permissions:
+      actions: read
+    steps:
+      - name: Get image name
+        shell: bash
+        id: image_name
+        run: |
+          if [ "${{ github.event.release.prerelease }}" != "true" ]; then
+            echo "Image name: NSPanelManager-{arch}"
+            echo "image_name=NSPanelManager-{arch}" >> $GITHUB_OUTPUT
+            echo "branch=main" >> $GITHUB_OUTPUT
+          elif [ "${{ github.event.release.prerelease }}" == "true" ]; then
+            echo "Image name: NSPanelManager-beta-{arch}"
+            echo "image_name=NSPanelManager-beta-{arch}" >> $GITHUB_OUTPUT
+            echo "branch=beta" >> $GITHUB_OUTPUT
+          else
+            echo "Cannot determine image name!"
+            exit 1
+          fi
+      - name: Login to DockerHub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - uses: yogeshlonkar/wait-for-jobs@v0
+        with:
+          jobs: 'prepare'
+      - name: Checkout the repository
+        uses: actions/checkout@v4
+      - name: Publish
+        uses: home-assistant/builder@master
+        with:
+          args: |
+            --aarch64 \
             --target docker \
             --image ${{ steps.image_name.outputs.image_name }} \
             --version ${{ github.ref_name }} \
