Fixed bug in workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -20,6 +20,18 @@ jobs:
       - run: |
           sed -i "s/^version: [0-9\.]\+/version: ${{ github.ref_name }}/g" docker/config.yaml
           sed -i '/^[ \t]/s/.*/  ${{ github.ref_name }}/g' docker/web/nspanelmanager/web/templates/footer.html
+      - name: Get branch name
+        shell: bash
+        id: image_name
+        run: |
+          if [ "${{ github.event.release.prerelease }}" != "true" ]; then
+            echo "branch=main" >> $GITHUB_OUTPUT
+          elif [ "${{ github.event.release.prerelease }}" == "true" ]; then
+            echo "branch=beta" >> $GITHUB_OUTPUT
+          else
+            echo "Cannot determine image name!"
+            exit 1
+          fi
       - uses: stefanzweifel/git-auto-commit-action@v5
         if: ${{ !github.event.act }} # skip during local actions testing
         with:
